first_name = input("What is your name?")
print(f"Hello {first_name}")
best = input("Who is the best?")
print(f"NO! {best} is not the best, I am the best!")
first_name = input("What is your name?")
print(f"Hello {first_name}")
best = input("Who is the best?")
print(f"NO! {best} is not the best, I am the best!")
first_name = input("What is your name?")
print(f"Hello {first_name}")
best = input("Who is the best?")
print(f"NO! {best} is not the best, I am the best!")
first_name = input("What is your name?")
print(f"Hello {first_name}")
best = input("Who is the best?")
print(f"NO! {best} is not the best, I am the best!")
first_name = input("What is your name?")
print(f"Hello {first_name}")
best = input("Who is the best?")
print(f"NO! {best} is not the best, I am the best!")
first_name = input("What is your name?")
print(f"Hello {first_name}")
best = input("Who is the best?")
print(f"NO! {best} is not the best, I am the best!")

